# Generated by Django 5.2.4 on 2025-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "type",
                    models.CharField(
                        choices=[("counseling", "مشاوره"), ("message", "ارتباط با ما")],
                        max_length=255,
                        verbose_name="نوع پیام",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=255, verbose_name="شماره تماس"),
                ),
                (
                    "industry",
                    models.CharField(max_length=255, verbose_name="زمینه فعالیت"),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="متن پیام"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "تماس",
                "verbose_name_plural": "1. تماس ها",
            },
        ),
    ]
