# Generated by Django 5.2.4 on 2025-07-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="seen",
            field=models.BooleanField(default=False, verbose_name="خوانده شده"),
        ),
    ]
