# Generated by Django 5.2.6 on 2025-09-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_durabilitytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AlterField(
            model_name='durabilitytest',
            name='user_phone',
            field=models.CharField(max_length=15),
        ),
    ]
